# Generated by Django 5.2.4 on 2025-07-28 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_stay', models.CharField(choices=[(' учеба', 'Учеба в университете/школе'), (' работа', 'Работа'), ('воссоединение', 'Воссоединение с семьей'), ('другое', 'Другое')], max_length=50, verbose_name='Основная цель пребывания')),
                ('purpose_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другая цель (укажите)')),
                ('surname_latin', models.CharField(max_length=100, verbose_name='Фамилия (латиницей)')),
                ('name_latin', models.CharField(max_length=100, verbose_name='Имя (имена) (латиницей)')),
                ('previous_name_surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Предыдущие имя и фамилия')),
                ('family_name', models.CharField(max_length=100, verbose_name='Родовая фамилия')),
                ('father_name', models.CharField(max_length=100, verbose_name='Имя отца')),
                ('mother_name', models.CharField(max_length=100, verbose_name='Имя матери')),
                ('mother_maiden_name', models.CharField(max_length=100, verbose_name='Девичья фамилия матери')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Место рождения (город)')),
                ('country_of_birth', models.CharField(max_length=100, verbose_name='Страна рождения')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальность')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Семейное положение')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер PESEL (если есть)')),
                ('height', models.PositiveIntegerField(verbose_name='Рост (в см)')),
                ('eye_color', models.CharField(max_length=50, verbose_name='Цвет глаз')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Контактный телефон (польский)')),
                ('voivodeship', models.CharField(max_length=100, verbose_name='Воеводство')),
                ('city', models.CharField(max_length=100, verbose_name='Город/Населенный пункт')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер квартиры')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('last_entry_date', models.DateField(verbose_name='Дата последнего въезда в Польшу')),
                ('legal_basis_of_stay', models.CharField(choices=[('виза', 'Виза'), ('безвиз', 'Безвиз'), ('карта', 'Карта побыту')], max_length=50, verbose_name='Основание для текущего пребывания')),
                ('source_of_funds', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник средств к существованию (для учебы)')),
                ('photo', models.FileField(upload_to='client_documents/', verbose_name='Фотография')),
                ('passport_scan', models.FileField(upload_to='client_documents/', verbose_name='Скан паспорта')),
                ('rental_agreement', models.FileField(upload_to='client_documents/', verbose_name='Договор аренды')),
                ('health_insurance', models.FileField(upload_to='client_documents/', verbose_name='Медицинская страховка')),
                ('proof_of_study', models.FileField(blank=True, null=True, upload_to='client_documents/', verbose_name='Справка из учебного заведения')),
                ('proof_of_funds', models.FileField(blank=True, null=True, upload_to='client_documents/', verbose_name='Подтверждение наличия средств')),
                ('work_attachment_1', models.FileField(blank=True, null=True, upload_to='client_documents/', verbose_name='Załącznik nr 1 (от работодателя)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
