[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = skip
check_untyped_defs = True
allow_untyped_defs = True
allow_incomplete_defs = True
warn_unused_ignores = True
disable_error_code = import-untyped, misc, call-overload
exclude = (?x)(migrations/|tests/|venv/|\.venv/|tmp/|scratch/)

[mypy-*.migrations.*]
ignore_errors = True
