[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = True
allow_untyped_defs = False
allow_incomplete_defs = False
warn_unused_ignores = True
disable_error_code = import-untyped
exclude = (?x)(migrations/|tests/|venv/|\.venv/|tmp/|scratch/|generated_media_test/|(^|/)media/|staticfiles/|logs/)
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = legalize_site.settings.test

[mypy-*.migrations.*]
ignore_errors = True
