[phases.setup]
# Force cache invalidation
# Use the system Python provided by Railway's Nixpacks
nixPkgs = ["python312", "pip", "nix"]
aptPkgs = ["gettext", "fonts-dejavu-core", "fonts-noto-core", "tesseract-ocr", "tesseract-ocr-eng", "tesseract-ocr-pol", "poppler-utils", "postgresql-client"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py compilemessages --ignore 'venv' --ignore '.venv'",
  "python manage.py collectstatic --no-input"
]

[start]
cmd = "bash start.sh"
