[pytest]
DJANGO_SETTINGS_MODULE = legalize_site.settings.test
python_files = test_*.py
norecursedirs = .git .pytest_cache venv .venv tmp media generated_media_test staticfiles logs pytest-cache-files-*
addopts = --cov=clients --cov=submissions --cov=legalize_site --cov=users --cov-report=term-missing --no-cov-on-fail
