# Generated by Django 6.0.1 on 2026-01-29 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Сохраняем имя для случаев, если пользователь удален', max_length=150, verbose_name='Имя пользователя')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('login', 'Вход'), ('logout', 'Выход'), ('login_failed', 'Неудачный вход'), ('view', 'Просмотр'), ('export', 'Экспорт'), ('email_sent', 'Отправка email'), ('ocr_parse', 'OCR парсинг'), ('file_upload', 'Загрузка файла'), ('file_delete', 'Удаление файла'), ('custom', 'Пользовательское действие')], db_index=True, max_length=20, verbose_name='Действие')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, help_text='Строковое представление объекта на момент действия', max_length=500, verbose_name='Представление объекта')),
                ('changes', models.JSONField(blank=True, help_text='Детали изменений в формате JSON', null=True, verbose_name='Изменения')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание действия', verbose_name='Описание')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Путь запроса')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP метод')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, выполнивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditlog_time_idx'), models.Index(fields=['user', '-timestamp'], name='auditlog_user_time_idx'), models.Index(fields=['action', '-timestamp'], name='auditlog_action_time_idx'), models.Index(fields=['content_type', '-timestamp'], name='auditlog_ctype_time_idx'), models.Index(fields=['ip_address', '-timestamp'], name='auditlog_ip_time_idx')],
            },
        ),
    ]
