# Generated by Django 5.1.7 on 2025-07-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_employer_phone_client_fingerprints_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи (Złożone)'),
        ),
    ]
