# Generated by Django 5.1.7 on 2025-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции (если есть)'),
        ),
    ]
