# Generated by Django 5.1.7 on 2025-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
