# Generated by Django 5.1.7 on 2025-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('certificate_enrolment', 'Справка о зачислении')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
