# Generated by Django 5.1.7 on 2025-07-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='clients.document'),
        ),
    ]
