# Generated by Django 6.0.1 on 2025-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_document_expiry_date_reminder_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_checklist_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к чеклисту предоставлен'),
        ),
    ]
