# Generated by Django 5.2.4 on 2025-09-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_client_has_checklist_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service_description',
            field=models.CharField(choices=[('work_service', 'Работа'), ('study_service', 'Учеба'), ('consultation', 'Консультация')], max_length=100, verbose_name='Описание услуги'),
        ),
    ]
