# Generated by Django 5.2.8 on 2025-11-22 19:15

from django.db import migrations, models

from clients.constants import DOCUMENT_CHECKLIST


def load_default_requirements(apps, schema_editor):
    DocumentRequirement = apps.get_model('clients', 'DocumentRequirement')

    positions = {}
    for (purpose, _lang), documents in DOCUMENT_CHECKLIST.items():
        seen = positions.setdefault(purpose, set())
        for idx, (code, _name) in enumerate(documents):
            if code in seen:
                continue
            DocumentRequirement.objects.update_or_create(
                application_purpose=purpose,
                document_type=code,
                defaults={'position': idx, 'is_required': True},
            )
            seen.add(code)


def clear_requirements(apps, schema_editor):
    DocumentRequirement = apps.get_model('clients', 'DocumentRequirement')
    DocumentRequirement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_alter_payment_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("photos", "Фотографии"),
                    ("payment_confirmation", "Подтверждение оплаты"),
                    ("passport", "Паспорт"),
                    ("enrollment_certificate", "Справка о зачислении"),
                    ("tuition_fee_proof", "Справка об оплате обучения"),
                    ("health_insurance", "Медицинская страховка"),
                    ("address_proof", "Подтверждение адреса"),
                    ("financial_proof", "Подтверждение финансов"),
                    ("załącznik_nr_1", "Załącznik nr 1"),
                    ("employment_contract", "Трудовой договор"),
                    ("pit_proof", "PIT-37 / Zaświadczenie o niezaleganiu"),
                    (
                        "tax_clearance_employer",
                        "Справка об отсутствии налоговой задолженности работодателя",
                    ),
                    (
                        "tax_clearance_foreigner",
                        "Справка об отсутствии налоговой задолженности иностранца",
                    ),
                    (
                        "no_dependents_statement",
                        "Заявление об отсутствии иждивенцев в Польше",
                    ),
                ],
                max_length=50,
                verbose_name="Тип документа",
            ),
        ),
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_purpose",
                    models.CharField(
                        choices=[
                            ("study", "Учёба"),
                            ("work", "Работа"),
                            ("family", "Воссоединение семьи"),
                        ],
                        max_length=20,
                        verbose_name="Цель подачи",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("photos", "Фотографии"),
                            ("payment_confirmation", "Подтверждение оплаты"),
                            ("passport", "Паспорт"),
                            ("enrollment_certificate", "Справка о зачислении"),
                            ("tuition_fee_proof", "Справка об оплате обучения"),
                            ("health_insurance", "Медицинская страховка"),
                            ("address_proof", "Подтверждение адреса"),
                            ("financial_proof", "Подтверждение финансов"),
                            ("załącznik_nr_1", "Załącznik nr 1"),
                            ("employment_contract", "Трудовой договор"),
                            ("pit_proof", "PIT-37 / Zaświadczenie o niezaleganiu"),
                            (
                                "tax_clearance_employer",
                                "Справка об отсутствии налоговой задолженности работодателя",
                            ),
                            (
                                "tax_clearance_foreigner",
                                "Справка об отсутствии налоговой задолженности иностранца",
                            ),
                            (
                                "no_dependents_statement",
                                "Заявление об отсутствии иждивенцев в Польше",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный документ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование к документу",
                "verbose_name_plural": "Требования к документам",
                "ordering": ["position", "id"],
                "unique_together": {("application_purpose", "document_type")},
            },
        ),
        migrations.RunPython(load_default_requirements, reverse_code=clear_requirements),
    ]
