# Generated by Django 5.2.8 on 2025-11-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_documentrequirement_custom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=100, verbose_name="Тип документа"),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="custom_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название документа"
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="document_type",
            field=models.CharField(max_length=100, verbose_name="Код типа документа"),
        ),
    ]
