# Generated by Django 5.2.8 on 2025-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InpolProceedingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proceeding_id", models.CharField(max_length=255, unique=True)),
                ("case_number", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "proceeding_id"],
            },
        ),
    ]
