# Generated by Django 5.2.8 on 2025-11-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_inpolproceedingsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="inpol_status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Статус inPOL"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="inpol_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обновления inPOL"
            ),
        ),
    ]
