# Generated by Django 5.2.8 on 2025-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0022_client_inpol_status_client_inpol_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="InpolAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название учётки"),
                ),
                ("base_url", models.URLField(verbose_name="Базовый URL inPOL")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email для входа"),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Пароль для входа"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Учётная запись inPOL",
                "verbose_name_plural": "Учётные записи inPOL",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
