# Generated by Django 5.2.8 on 2025-11-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_inpolaccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InpolAccount",
        ),
        migrations.DeleteModel(
            name="InpolProceedingSnapshot",
        ),
        migrations.RemoveField(
            model_name="client",
            name="inpol_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="inpol_updated_at",
        ),
    ]
