# Generated by Django 5.2.8 on 2025-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0024_delete_inpolaccount_delete_inpolproceedingsnapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(max_length=255, verbose_name="Тип документа"),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="custom_name",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Название документа"
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="document_type",
            field=models.CharField(max_length=255, verbose_name="Код типа документа"),
        ),
    ]
