# Generated by Django 5.2.8 on 2025-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0025_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("pl", "Polski"), ("en", "English")],
                default="pl",
                max_length=5,
                verbose_name="Язык документов",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="application_purpose",
            field=models.CharField(max_length=50, verbose_name="Цель подачи"),
        ),
    ]
