# Generated by Django 5.2.8 on 2025-11-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0026_alter_client_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
