# Generated by Django 5.2.8 on 2025-12-01 10:15

import hashlib

from cryptography.fernet import Fernet, InvalidToken, MultiFernet
from django.conf import settings
from django.db import migrations, models
import fernet_fields


def _build_fernet() -> MultiFernet | None:
    keys = getattr(settings, "FERNET_KEYS", []) or []
    if not keys:
        return None
    fernets = []
    for key in keys:
        if isinstance(key, str):
            fernets.append(Fernet(key.encode("utf-8")))
        else:
            fernets.append(Fernet(key))
    return MultiFernet(fernets)


def _hash_case_number(value: str) -> str:
    normalized = value.strip().upper().replace(" ", "")
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def encrypt_existing_pii(apps, schema_editor):
    fernet = _build_fernet()
    if not fernet:
        return

    Client = apps.get_model("clients", "Client")
    for client in Client.objects.all():
        updated = False

        case_number_value = client.case_number
        if case_number_value:
            try:
                decrypted = fernet.decrypt(case_number_value.encode("utf-8")).decode("utf-8")
                encrypted_value = case_number_value
            except (InvalidToken, ValueError, TypeError):
                decrypted = case_number_value
                encrypted_value = fernet.encrypt(case_number_value.encode("utf-8")).decode("utf-8")
            client.case_number = encrypted_value
            client.case_number_hash = _hash_case_number(decrypted)
            updated = True
        elif client.case_number_hash:
            client.case_number_hash = None
            updated = True

        passport_value = client.passport_num
        if passport_value:
            try:
                fernet.decrypt(passport_value.encode("utf-8"))
                encrypted_value = passport_value
            except (InvalidToken, ValueError, TypeError):
                encrypted_value = fernet.encrypt(passport_value.encode("utf-8")).decode("utf-8")
            client.passport_num = encrypted_value
            updated = True

        if updated:
            client.save(update_fields=["case_number", "case_number_hash", "passport_num"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0027_client_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="passport_num",
            field=models.TextField(blank=True, null=True, verbose_name="Номер паспорта"),
        ),
        migrations.AlterField(
            model_name="client",
            name="case_number",
            field=models.TextField(blank=True, null=True, verbose_name="Номер дела"),
        ),
        migrations.AddField(
            model_name="client",
            name="case_number_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(encrypt_existing_pii, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="client",
            name="passport_num",
            field=fernet_fields.EncryptedTextField(blank=True, null=True, verbose_name="Номер паспорта"),
        ),
        migrations.AlterField(
            model_name="client",
            name="case_number",
            field=fernet_fields.EncryptedTextField(blank=True, null=True, verbose_name="Номер дела"),
        ),
    ]
