# Generated by Django 6.0.1 on 2026-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0028_encrypt_client_pii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="application_purpose",
            field=models.CharField(
                default="study", max_length=64, verbose_name="Цель подачи"
            ),
        ),
    ]
