# Generated by Django 6.0.1 on 2026-01-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0029_alter_client_application_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequirement",
            name="custom_name_en",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Название документа (EN)",
            ),
        ),
        migrations.AddField(
            model_name="documentrequirement",
            name="custom_name_pl",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Название документа (PL)",
            ),
        ),
        migrations.AddField(
            model_name="documentrequirement",
            name="custom_name_ru",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Название документа (RU)",
            ),
        ),
    ]
