# Generated by Django 6.0.1 on 2026-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_documentrequirement_custom_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата официальной децизии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_description',
            field=models.CharField(choices=[('work_service', 'Работа'), ('study_service', 'Учёба'), ('consultation', 'Консультация')], max_length=100, verbose_name='Описание услуги'),
        ),
    ]
