# Generated by Django 6.0.1 on 2026-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_document_awaiting_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fingerprints_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место сдачи отпечатков'),
        ),
        migrations.AddField(
            model_name='client',
            name='fingerprints_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время сдачи отпечатков'),
        ),
    ]
