# Generated by Django 6.0.1 on 2026-03-24 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0034_client_fingerprints_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('recipients', models.CharField(max_length=500, verbose_name='Получатели')),
                ('template_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип шаблона')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='clients.client', verbose_name='Клиент')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Журнал email',
                'verbose_name_plural': 'Журнал email',
                'ordering': ['-sent_at'],
            },
        ),
    ]
