# Generated by Django 6.0.1 on 2026-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_add_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(choices=[('work_service', 'Работа'), ('study_service', 'Учёба'), ('consultation', 'Консультация')], max_length=50, unique=True, verbose_name='Код услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (PLN)')),
            ],
            options={
                'verbose_name': 'Цена на услугу',
                'verbose_name_plural': 'Цены на услуги',
            },
        ),
    ]
