# Generated by Django 6.0.1 on 2026-04-19 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_clientactivity_stafftask_client_workflow_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_name_mismatch',
            field=models.BooleanField(default=False, verbose_name='Несовпадение имени OCR'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('skipped', 'Пропущено'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('pending', 'Ожидает')], default='skipped', max_length=20, verbose_name='Статус OCR'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Отправка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_details', models.TextField(blank=True, default='', verbose_name='Детали ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Email-кампания',
                'verbose_name_plural': 'Email-кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_versions/', verbose_name='Файл версии')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clients.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
