# Generated by Django 6.0.1 on 2026-04-20 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0040_document_ocr_name_mismatch_document_ocr_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentProcessingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_type", models.CharField(choices=[("wezwanie_ocr", "Wezwanie OCR")], default="wezwanie_ocr", max_length=50, verbose_name="Job type")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="pending", max_length=20, verbose_name="Status")),
                ("source_file_name", models.CharField(blank=True, default="", max_length=500, verbose_name="Source file name")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="Attempts")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Error message")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Started at")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_processing_jobs", to=settings.AUTH_USER_MODEL, verbose_name="Created by")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processing_jobs", to="clients.document", verbose_name="Document")),
            ],
            options={
                "verbose_name": "Document processing job",
                "verbose_name_plural": "Document processing jobs",
                "ordering": ["created_at"],
                "unique_together": {("document", "job_type")},
            },
        ),
    ]
