# Generated by Django 6.0.1 on 2026-04-20 21:10

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_documentprocessingjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[clients.validators.validate_uploaded_document], verbose_name='Файл'),
        ),
    ]
