# Generated by Django 6.0.1 on 2026-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0042_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="filters_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Фильтры"),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="recipient_emails",
            field=models.JSONField(blank=True, default=list, verbose_name="Получатели"),
        ),
        migrations.AddField(
            model_name="emailcampaign",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Запущено"),
        ),
    ]
