# Generated by Django 6.0.1 on 2026-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_client_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='event_type',
            field=models.CharField(choices=[('client_viewed', 'Карточка клиента открыта'), ('client_created', 'Клиент создан'), ('client_updated', 'Данные клиента изменены'), ('workflow_changed', 'Этап workflow изменён'), ('document_uploaded', 'Документ загружен'), ('document_downloaded', 'Документ открыт'), ('document_deleted', 'Документ удалён'), ('document_verified', 'Статус документа изменён'), ('document_version_restored', 'Версия документа восстановлена'), ('email_sent', 'Письмо отправлено'), ('client_exported', 'Данные клиента экспортированы'), ('wniosek_attachment_deleted', 'Отметка wniosek удалена'), ('reminder_deactivated', 'Напоминание отмечено выполненным'), ('reminder_deleted', 'Напоминание удалено'), ('payment_created', 'Платёж создан'), ('payment_updated', 'Платёж обновлён'), ('payment_deleted', 'Платёж удалён'), ('task_created', 'Задача создана'), ('task_completed', 'Задача завершена'), ('note_updated', 'Заметка обновлена')], max_length=50, verbose_name='Тип события'),
        ),
    ]
