# Generated by Django 6.0.1 on 2026-04-22 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_alter_clientactivity_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='delivery_status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], default='sent', max_length=20, verbose_name='Статус доставки'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка доставки'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AddConstraint(
            model_name='emaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='clients_emaillog_unique_idempotency_key'),
        ),
    ]
