# Generated by Django 6.0.1 on 2026-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_emaillog_delivery_status_emaillog_error_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='client',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
