# Generated by Django 6.0.1 on 2026-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0050_alter_clientactivity_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessingjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lease expires at'),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Max attempts'),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next attempt at'),
        ),
    ]
