# Generated by Django 6.0.1 on 2026-04-24 21:42

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0051_documentprocessingjob_lease_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="error_details",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="Детали ошибок"
            ),
        ),
        migrations.AlterField(
            model_name="emailcampaign",
            name="message",
            field=fernet_fields.fields.EncryptedTextField(verbose_name="Текст письма"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="body",
            field=fernet_fields.fields.EncryptedTextField(verbose_name="Текст письма"),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="error_message",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="Ошибка доставки"
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="recipients",
            field=fernet_fields.fields.EncryptedTextField(verbose_name="Получатели"),
        ),
    ]
