# Generated by Django 6.0.4 on 2026-04-27 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_documentprocessingjob_lease_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_staff', 'status'], name='client_staff_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workflow_stage', 'status'], name='client_workflow_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='client_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client', 'document_type'], name='doc_client_type_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status', 'awaiting_confirmation'], name='doc_ocr_confirm_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessingjob',
            index=models.Index(fields=['job_type', 'status', 'next_attempt_at'], name='docjob_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessingjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='docjob_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['application_purpose', 'position'], name='docreq_purpose_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'status'], name='payment_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='payment_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_active', 'due_date'], name='reminder_active_due_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['client', 'is_active'], name='reminder_client_active_idx'),
        ),
    ]
