# Generated by Django 6.0.4 on 2026-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0052_alter_client_options_client_client_staff_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Распознанные данные'),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='Requires confirmation'),
        ),
    ]
