# Generated by Django 6.0.1 on 2026-04-25 14:50

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0052_alter_emailcampaign_error_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="recipient_emails",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="[]", verbose_name="Получатели"
            ),
        ),
    ]
