# Generated by Django 6.0.1 on 2026-04-26 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0053_alter_emailcampaign_recipient_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage_payments", models.BooleanField(default=False)),
                ("can_send_custom_email", models.BooleanField(default=False)),
                ("can_send_mass_email", models.BooleanField(default=False)),
                ("can_export_clients", models.BooleanField(default=False)),
                ("can_delete_clients", models.BooleanField(default=False)),
                ("can_delete_documents", models.BooleanField(default=False)),
                ("can_manage_checklists", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_manage_staff_tasks", models.BooleanField(default=False)),
                ("can_run_ocr_review", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee permission",
                "verbose_name_plural": "Employee permissions",
            },
        ),
    ]
