# Generated by Django 6.0.1 on 2026-04-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_document_parsed_data_and_more'),
        ('clients', '0054_employeepermission'),
    ]

    operations = [
    ]
