# Generated by Django 6.0.1 on 2026-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_merge_20260427_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fingerprints_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация (кабинет, окно и т.д.)'),
        ),
        migrations.AddField(
            model_name='client',
            name='fingerprints_list',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название списка (Lista)'),
        ),
        migrations.AddField(
            model_name='client',
            name='fingerprints_ticket',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер билета (Bilet)'),
        ),
    ]
