# Generated by Django 6.0.4 on 2026-04-30 22:42

import clients.models.document
import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_client_fingerprints_info_client_fingerprints_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=clients.models.document.document_upload_path, validators=[clients.validators.validate_uploaded_document], verbose_name='Файл'),
        ),
    ]
