# Generated by Django 6.0.4 on 2026-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка')], default='sent', max_length=20, verbose_name='Статус доставки'),
        ),
    ]
