# Generated by Django 6.0.4 on 2026-05-03 18:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_alter_emaillog_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доход спонсора')),
                ('monthly_support_per_person', models.DecimalField(decimal_places=2, default=Decimal('823.00'), max_digits=10, verbose_name='Ежемесячное содержание')),
                ('monthly_housing_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость жилья')),
                ('meldunek_free_housing', models.BooleanField(default=False, verbose_name='Meldunek / бесплатное жильё')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Семейная группа',
                'verbose_name_plural': 'Семейные группы',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='family_role',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('sponsor', 'Спонсор'), ('family_spouse', 'Супруг/супруга'), ('family_child', 'Ребёнок')], default='', max_length=32, verbose_name='Роль в семье'),
        ),
        migrations.AddField(
            model_name='client',
            name='sponsor_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_family_members', to='clients.client', verbose_name='Спонсор'),
        ),
        migrations.AddField(
            model_name='document',
            name='zus_period_month',
            field=models.DateField(blank=True, help_text='Первый день месяца, за который загружен ZUS RCA.', null=True, verbose_name='ZUS RCA — месяц'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['sponsor_client', 'family_role'], name='client_family_role_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client', 'document_type', 'zus_period_month'], name='doc_zus_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'zus_rca_or_insurance'), ('zus_period_month__isnull', False)), fields=('client', 'document_type', 'zus_period_month'), name='unique_zus_rca_period_per_client'),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='sponsor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_group', to='clients.client', verbose_name='Спонсор'),
        ),
    ]
