# Generated by Django 6.0.5 on 2026-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0063_rename_no_dependents_to_tax_clearance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='payment_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='payment_amount_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total_amount'))), name='payment_amount_paid_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), ('amount_paid', 0), _connector='OR'), name='payment_pending_amount_zero'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('amount_paid', models.F('total_amount')), _connector='OR'), name='payment_paid_amount_matches_total'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'partial'), _negated=True), models.Q(('amount_paid__gt', 0), ('amount_paid__lt', models.F('total_amount'))), _connector='OR'), name='payment_partial_amount_between'),
        ),
    ]
