# Generated by Django 6.0.5 on 2026-05-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0064_payment_payment_total_amount_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('staff_updated', 'Staff user updated'), ('staff_active_toggled', 'Staff active status toggled')], max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_audit_events', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_staff_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff audit event',
                'verbose_name_plural': 'Staff audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target', '-created_at'], name='staffaudit_target_created_idx'), models.Index(fields=['actor', '-created_at'], name='staffaudit_actor_created_idx')],
            },
        ),
    ]
