# Generated by Django 6.0.5 on 2026-05-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0066_clientactivity_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientactivity',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clients.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clients.payment', verbose_name='Платёж'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clients.stafftask', verbose_name='Задача'),
        ),
    ]
