# Generated by Django 6.0.5 on 2026-05-19 21:31

from django.db import migrations, models


def migrate_legacy_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            # Check if 'action' column exists in 'clients_clientactivity' table
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name='clients_clientactivity' AND column_name='action'
                );
            """)
            if cursor.fetchone()[0]:
                cursor.execute("ALTER TABLE clients_clientactivity RENAME COLUMN action TO event_type;")
                cursor.execute("ALTER TABLE clients_clientactivity ALTER COLUMN event_type TYPE varchar(50) USING LEFT(event_type, 50);")
                cursor.execute("UPDATE clients_clientactivity SET actor_id = user_id WHERE actor_id IS NULL AND user_id IS NOT NULL;")
                cursor.execute("ALTER TABLE clients_clientactivity DROP COLUMN user_id;")


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_clientactivity_document_clientactivity_payment_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='clientactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='summary',
            field=models.CharField(default='', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
