# Generated by Django 6.0.5 on 2026-05-19 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_clientactivity_document_clientactivity_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientactivity',
            name='event_type',
            field=models.CharField(
                choices=[('client_viewed', 'Карточка клиента открыта'), ('client_created', 'Клиент создан'), ('client_updated', 'Данные клиента изменены'), ('client_status_changed', 'Статус клиента изменён'), ('workflow_changed', 'Этап workflow изменён'), ('deadline_changed', 'Ключевая дата изменена'), ('document_uploaded', 'Документ загружен'), ('document_downloaded', 'Документ открыт'), ('document_deleted', 'Документ удалён'), ('document_verified', 'Статус документа изменён'), ('document_version_restored', 'Версия документа восстановлена'), ('email_sent', 'Письмо отправлено'), ('client_exported', 'Данные клиента экспортированы'), ('wniosek_attachment_deleted', 'Отметка wniosek удалена'), ('reminder_deactivated', 'Напоминание отмечено выполненным'), ('reminder_deleted', 'Напоминание удалено'), ('payment_created', 'Платёж создан'), ('payment_updated', 'Платёж обновлён'), ('payment_deleted', 'Платёж удалён'), ('task_created', 'Задача создана'), ('task_completed', 'Задача завершена'), ('note_updated', 'Заметка обновлена')],
                max_length=50,
                verbose_name='Тип события',
                default='unknown'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 19, 21, 26, 49, 232198, tzinfo=datetime.timezone.utc), verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='details',
            field=models.TextField(blank=True, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='summary',
            field=models.CharField(default='', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
