# Generated by Django 6.0.5 on 2026-05-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_clientactivity_document_clientactivity_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='clients.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='clients.payment', verbose_name='Платёж'),
        ),
    ]
