# Generated by Django 6.0.5 on 2026-05-23 18:01

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0070_client_client_email_idx_client_client_phone_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDigitalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_pesel', models.BooleanField(default=False)),
                ('pesel', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('pesel_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('pesel_verified', models.BooleanField(default=False)),
                ('has_trusted_profile', models.BooleanField(default=False)),
                ('trusted_profile_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('has_mos_account', models.BooleanField(default=False)),
                ('mos_account_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('needs_pesel_application', models.BooleanField(default=False)),
                ('needs_trusted_profile_instruction', models.BooleanField(default=False)),
                ('needs_mos_instruction', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_access', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFamilyMemberMOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'M'), ('K', 'K')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('residence_place', models.CharField(blank=True, max_length=255)),
                ('applies_for_temporary_residence', models.BooleanField(default=False)),
                ('is_dependent_on_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mos_family_members', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment_pending', 'Payment pending'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='created', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='clients.client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.payment')),
            ],
        ),
        migrations.CreateModel(
            name='MOSApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('client_filling', 'Client filling'), ('client_completed', 'Client completed'), ('staff_review', 'Staff review'), ('needs_correction', 'Needs correction'), ('approved_by_staff', 'Approved by staff'), ('mos_package_ready', 'MOS package ready'), ('submitted_in_mos', 'Submitted in MOS'), ('fingerprints', 'Fingerprints'), ('waiting_decision', 'Waiting decision'), ('decision_received', 'Decision received'), ('closed', 'Closed')], default='draft', max_length=40)),
                ('mos_purpose', models.CharField(blank=True, max_length=64)),
                ('legal_stay_until', models.DateField(blank=True, null=True, verbose_name='Legal stay valid until')),
                ('personal_data', models.JSONField(blank=True, default=dict)),
                ('passport_data', models.JSONField(blank=True, default=dict)),
                ('address_data', models.JSONField(blank=True, default=dict)),
                ('stay_data', models.JSONField(blank=True, default=dict)),
                ('previous_stays', models.JSONField(blank=True, default=list)),
                ('travel_history', models.JSONField(blank=True, default=list)),
                ('insurance_data', models.JSONField(blank=True, default=dict)),
                ('financial_data', models.JSONField(blank=True, default=dict)),
                ('legal_declarations', models.JSONField(blank=True, default=dict)),
                ('justification', models.TextField(blank=True)),
                ('client_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('correction_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mos_application_data', to='clients.client')),
                ('staff_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mos_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeselApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_needed', 'Not needed'), ('needs_data', 'Needs data'), ('data_completed', 'Data completed'), ('staff_review', 'Staff review'), ('draft_ready', 'Draft ready'), ('sent_to_client', 'Sent to client'), ('waiting_for_client_visit', 'Waiting for client visit'), ('pesel_received', 'PESEL received'), ('cancelled', 'Cancelled')], default='needs_data', max_length=40)),
                ('legal_basis', models.TextField(blank=True)),
                ('pesel_form_data', models.JSONField(blank=True, default=dict)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='pesel_applications/')),
                ('signed_scan', models.FileField(blank=True, null=True, upload_to='pesel_signed/')),
                ('staff_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesel_applications', to='clients.client')),
                ('staff_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_pesel_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
