# Generated by Django 6.0.5 on 2026-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_clientdigitalaccess_clientfamilymembermos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('pl', 'Polski'), ('en', 'English'), ('uk', 'Українська')], default='pl', max_length=5, verbose_name='Язык документов'),
        ),
    ]
