# Generated by Django 6.0.5 on 2026-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_alter_client_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
