# Generated by Django 6.0.5 on 2026-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0073_alter_client_citizenship_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('wezwanie_ocr', 'Wezwanie OCR'), ('company_doc_ocr', 'Company Doc OCR')], default='wezwanie_ocr', max_length=50, verbose_name='Job type'),
        ),
    ]
