# Generated by Django 6.0.5 on 2026-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0074_alter_documentprocessingjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('wezwanie_ocr', 'Wezwanie OCR'), ('company_doc_ocr', 'Company Doc OCR'), ('passport_ocr', 'Passport OCR'), ('rental_ocr', 'Rental Agreement OCR'), ('zus_ocr', 'ZUS Documents OCR'), ('insurance_ocr', 'Insurance Policy OCR')], default='wezwanie_ocr', max_length=50, verbose_name='Job type'),
        ),
    ]
