# Generated by Django 6.0.5 on 2026-05-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_normalize_document_ocr_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_zus_rca_period_per_client',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='documentrequirement',
                    name='docreq_purpose_pos_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL('DROP INDEX IF EXISTS "docreq_purpose_pos_idx";'),
            ],
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='application_purpose',
            field=models.CharField(max_length=20, verbose_name='Цель подачи'),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='custom_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='custom_name_pl',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (PL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='custom_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='document_type',
            field=models.CharField(max_length=255, verbose_name='Тип документа'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('document_type', 'zus_rca_or_insurance'), ('zus_period_month__isnull', False)), fields=('client', 'document_type', 'zus_period_month'), name='unique_zus_rca_period_per_client'),
        ),
    ]
