# Generated by Django 6.0.5 on 2026-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0077_remove_document_unique_zus_rca_period_per_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("payment", "Оплата"),
                    ("document", "Документ"),
                    ("legal_stay", "Легальное пребывание"),
                    ("other", "Другое"),
                ],
                default="document",
                max_length=20,
                verbose_name="Тип напоминания",
            ),
        ),
    ]
