# Generated by Django 6.0.5 on 2026-05-26 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0078_alter_reminder_reminder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_required", models.BooleanField(default=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_document_requirements",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_client_document_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="reminder",
            name="custom_document_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="clients.clientdocumentrequirement",
            ),
        ),
        migrations.AddIndex(
            model_name="clientdocumentrequirement",
            index=models.Index(
                fields=["client", "is_active"], name="cl_doc_req_cl_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientdocumentrequirement",
            index=models.Index(
                fields=["document_type"], name="cl_doc_req_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientdocumentrequirement",
            index=models.Index(fields=["due_date"], name="cl_doc_req_due_idx"),
        ),
    ]
