# Generated by Django 6.0.5 on 2026-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0079_clientdocumentrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('pl', 'Polski'), ('en', 'English')], default='pl', max_length=5, verbose_name='Язык документов'),
        ),
    ]
