# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0080_alter_client_language"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(sponsor_client__isnull=True) | ~models.Q(id=models.F("sponsor_client_id")),
                name="client_no_self_sponsor",
            ),
        ),
    ]
