# Generated by Django 6.0.5 on 2026-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0082_fix_residence_card_ru_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='document_samples/', verbose_name='Образец документа'),
        ),
    ]
