# Generated by Django 6.0.5 on 2026-06-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0083_documentrequirement_sample_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_sensitive_data', 'Can view sensitive and encrypted PII data')]},
        ),
    ]
