# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0085_test_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrun",
            name="mode",
            field=models.CharField(
                choices=[
                    ("smoke", "Smoke"),
                    ("full", "Full"),
                    ("ocr", "OCR"),
                    ("email", "Email reminders"),
                    ("zus", "ZUS RCA"),
                    ("documents", "Document access"),
                    ("permissions", "Permissions"),
                    ("security", "Security"),
                    ("workflow", "Workflow"),
                ],
                max_length=32,
            ),
        ),
    ]
