# Generated by Django 6.0.5 on 2026-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0087_new_residence_card_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='clientonboardingsession',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='staffauditevent',
            name='is_demo_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
