# Generated by Django 6.0.6 on 2026-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0088_client_is_demo_data_clientactivity_is_demo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='workflow_stage',
            field=models.CharField(choices=[('new_client', 'Новый клиент'), ('document_collection', 'Сбор документов'), ('application_submitted', 'Подано в ужонд'), ('fingerprints', 'Ожидание отпечатков'), ('waiting_decision', 'Ожидание решения'), ('decision_received', 'Децизия'), ('closed', 'Закрыто')], default='new_client', max_length=32, verbose_name='Этап workflow'),
        ),
    ]
