# Generated by Django 6.0.6 on 2026-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0089_alter_client_workflow_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
