# Generated by Django 6.0.6 on 2026-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0090_document_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='is_auto_created',
            field=models.BooleanField(default=False, verbose_name='Создана автоматически'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='task_type',
            field=models.CharField(choices=[('document_review', 'Проверка документов'), ('missing_document', 'Недостающий документ'), ('zus_update', 'Обновление ZUS'), ('case_number_missing', 'Отсутствует номер дела'), ('fingerprints_followup', 'Контроль после отпечатков'), ('payment_followup', 'Контроль оплаты'), ('client_question', 'Вопрос клиента'), ('internal_note', 'Внутренняя заметка'), ('deadline_check', 'Контроль дедлайна')], default='internal_note', max_length=50, verbose_name='Тип задачи'),
        ),
    ]
