# Generated by Django 6.0.6 on 2026-06-22 05:48

import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_alter_clientactivity_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID дела')),
                ('internal_number', fernet_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Внутренний номер дела')),
                ('authority_case_number', fernet_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Номер дела в уженде')),
                ('authority_case_number_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('workflow_stage', models.CharField(choices=[('new_client', 'Новый клиент'), ('document_collection', 'Сбор документов'), ('application_submitted', 'Подано в ужонд'), ('fingerprints', 'Ожидание отпечатков'), ('waiting_decision', 'Ожидание решения'), ('decision_received', 'Децизия'), ('closed', 'Закрыто')], default='new_client', max_length=32, verbose_name='Этап workflow')),
                ('application_purpose', models.CharField(blank=True, default='', max_length=64, verbose_name='Основание легализации')),
                ('application_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип заявления')),
                ('basis_of_stay', models.CharField(blank=True, default='', max_length=100, verbose_name='Основание пребывания')),
                ('opened_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата открытия дела')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи')),
                ('fingerprints_date', models.DateField(blank=True, null=True, verbose_name='Дата отпечатков')),
                ('fingerprints_time', models.TimeField(blank=True, null=True, verbose_name='Время отпечатков')),
                ('fingerprints_location', models.CharField(blank=True, default='', max_length=255, verbose_name='Место отпечатков')),
                ('fingerprints_ticket', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер билета')),
                ('fingerprints_list', models.CharField(blank=True, default='', max_length=100, verbose_name='Lista')),
                ('fingerprints_info', models.TextField(blank=True, default='', verbose_name='Информация об отпечатках')),
                ('decision', models.TextField(blank=True, default='', verbose_name='Решение')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='Дата решения')),
                ('decision_valid_until', models.DateField(blank=True, null=True, verbose_name='Решение действительно до')),
                ('new_card_application_data', fernet_fields.fields.EncryptedJSONField(blank=True, default=dict, verbose_name='Данные новой подачи')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('close_reason', models.TextField(blank=True, default='', verbose_name='Причина закрытия')),
                ('last_archive_batch_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_test_data', models.BooleanField(db_index=True, default=False)),
                ('is_demo_data', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['-opened_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseArchiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_batch_uuid', models.UUIDField(db_index=True)),
                ('object_type', models.CharField(choices=[('document', 'Документ'), ('payment', 'Платёж'), ('reminder', 'Напоминание'), ('task', 'Задача'), ('portal_user', 'Пользователь портала')], max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('was_active', models.BooleanField(default=True)),
                ('previous_archived_at', models.DateTimeField(blank=True, null=True)),
                ('previous_reminder_is_active', models.BooleanField(blank=True, null=True)),
                ('previous_task_status', models.CharField(blank=True, default='', max_length=20)),
                ('previous_user_is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['archive_batch_uuid', 'object_type', 'object_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_zus_rca_period_per_client',
        ),
        migrations.AddField(
            model_name='clientdocumentrequirement',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='mosapplicationdata',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='peselapplication',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parsed_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, null=True, verbose_name='Распознанные данные'),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='address_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='financial_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='insurance_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='legal_declarations',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='passport_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='personal_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='previous_stays',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='stay_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='travel_history',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='peselapplication',
            name='pesel_form_data',
            field=fernet_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_cases', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='clients.company', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='clientdocumentrequirement',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_document_requirements', to='clients.case'),
        ),
        migrations.AddField(
            model_name='clientfamilymembermos',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mos_family_members', to='clients.case'),
        ),
        migrations.AddField(
            model_name='clientonboardingsession',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_sessions', to='clients.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_processing_jobs', to='clients.case', verbose_name='Case'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='mosapplicationdata',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mos_application_records', to='clients.case'),
        ),
        migrations.AddField(
            model_name='payment',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='peselapplication',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesel_applications', to='clients.case'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_tasks', to='clients.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='wnioseksubmission',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wniosek_submissions', to='clients.case', verbose_name='Case'),
        ),
        migrations.AddIndex(
            model_name='clientactivity',
            index=models.Index(fields=['case', '-created_at'], name='activity_case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocumentrequirement',
            index=models.Index(fields=['case', 'is_active'], name='cl_doc_req_case_act_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case', 'document_type'], name='doc_case_type_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessingjob',
            index=models.Index(fields=['case', 'status'], name='docjob_case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['case', '-sent_at'], name='emaillog_case_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['case', 'status'], name='payment_case_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['case', 'is_active'], name='reminder_case_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stafftask',
            index=models.Index(fields=['case', 'status', 'due_date'], name='task_case_status_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('case__isnull', False), ('document_type', 'zus_rca_or_insurance'), ('zus_period_month__isnull', False)), fields=('case', 'document_type', 'zus_period_month'), name='unique_zus_rca_period_per_case'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('payment__isnull', False), ('document__isnull', False), _negated=True), name='reminder_not_payment_and_document'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('payment__isnull', False), ('custom_document_requirement__isnull', False), _negated=True), name='reminder_not_payment_and_custom'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('document__isnull', False), ('custom_document_requirement__isnull', False), _negated=True), name='reminder_not_document_and_custom'),
        ),
        migrations.AddField(
            model_name='casearchivesnapshot',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_snapshots', to='clients.case'),
        ),
        migrations.AddField(
            model_name='casearchivesnapshot',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_archive_snapshots', to='clients.client'),
        ),
        migrations.AddField(
            model_name='casearchivesnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_archive_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client', 'archived_at'], name='case_client_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['workflow_stage', 'status'], name='case_workflow_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_staff', 'status'], name='case_staff_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['opened_at'], name='case_opened_at_idx'),
        ),
        migrations.AddIndex(
            model_name='casearchivesnapshot',
            index=models.Index(fields=['case', 'archive_batch_uuid'], name='case_snapshot_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='casearchivesnapshot',
            index=models.Index(fields=['object_type', 'object_id'], name='case_snapshot_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='casearchivesnapshot',
            constraint=models.UniqueConstraint(fields=('archive_batch_uuid', 'object_type', 'object_id'), name='unique_case_archive_snapshot_object'),
        ),
    ]
