# Generated by Django 6.0.6 on 2026-06-22 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0093_case_casearchivesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to='clients.case', verbose_name='Дело'),
        ),
    ]
