# Generated by Django 6.0.6 on 2026-06-22 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0094_documentversion_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['case', '-version_number'], name='docver_case_version_idx'),
        ),
    ]
