# Generated by Django 6.0.6 on 2026-06-22 16:34

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0096_backfill_cases_and_encrypt_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('archived', 'Архивировано'), ('restored', 'Восстановлено')], default='archived', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Главный заявитель'), ('spouse', 'Супруг(а)'), ('child', 'Ребенок'), ('parent', 'Родитель')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('archived', 'Архивировано'), ('restored', 'Восстановлено')], default='archived', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='legacy_case_number',
            field=fernet_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Предыдущий номер дела'),
        ),
        migrations.AddField(
            model_name='case',
            name='migration_origin',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Источник миграции'),
        ),
        migrations.AddField(
            model_name='case',
            name='needs_manual_number_check',
            field=models.BooleanField(default=False, verbose_name='Требуется ручная проверка номера'),
        ),
        migrations.AddField(
            model_name='clientonboardingsession',
            name='scope',
            field=models.CharField(choices=[('case_link', 'Ссылка на дело'), ('client_portal', 'Портал клиента')], default='case_link', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия метаданных'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия OCR'),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mos_application_data', to='clients.case'),
        ),
        migrations.AlterField(
            model_name='mosapplicationdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mos_applications', to='clients.client'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('migration_origin__isnull', False)), fields=('client', 'migration_origin'), name='unique_legacy_case_per_client'),
        ),
        migrations.AddConstraint(
            model_name='clientonboardingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case__isnull', False), ('scope', 'case_link')), models.Q(('case__isnull', True), ('scope', 'client_portal')), _connector='OR'), name='onboarding_scope_matches_case'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_type', 'legal_stay'), models.Q(('payment__isnull', False), ('document__isnull', False), ('custom_document_requirement__isnull', False), _connector='OR'), _negated=True), name='reminder_legal_stay_no_source'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_type', 'payment'), ('payment__isnull', True), _negated=True), name='reminder_payment_type_requires_payment'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('reminder_type', 'document'), ('document__isnull', True), ('custom_document_requirement__isnull', True), _negated=True), name='reminder_document_type_requires_source'),
        ),
        migrations.AddField(
            model_name='casearchivebatch',
            name='archived_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_case_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casearchivebatch',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_batches', to='clients.case'),
        ),
        migrations.AddField(
            model_name='casearchivebatch',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restored_case_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clients.case'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='sponsor_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_participants', to='clients.caseparticipant'),
        ),
        migrations.AddField(
            model_name='clientarchivebatch',
            name='archived_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_client_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientarchivebatch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_batches', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientarchivebatch',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restored_client_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casearchivebatch',
            name='client_archive_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_batches', to='clients.clientarchivebatch'),
        ),
        migrations.AddConstraint(
            model_name='caseparticipant',
            constraint=models.UniqueConstraint(fields=('case', 'client'), name='unique_case_client_participant'),
        ),
        migrations.AddConstraint(
            model_name='caseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'principal')), fields=('case',), name='one_principal_per_case'),
        ),
        migrations.AddConstraint(
            model_name='clientarchivebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived')), fields=('client',), name='one_open_archive_batch_per_client'),
        ),
        migrations.AddConstraint(
            model_name='casearchivebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived')), fields=('case',), name='one_open_archive_batch_per_case'),
        ),
    ]
