# Generated by Django 6.0.6 on 2026-06-22 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0099_correct_legacy_case_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата приостановки'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='suspended_by_archive_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_tasks', to='clients.casearchivebatch', verbose_name='Батч архивации'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='suspended_by_case_archive',
            field=models.BooleanField(default=False, verbose_name='Приостановлена архивацией дела'),
        ),
    ]
