# Generated by Django 6.0.6 on 2026-06-22 22:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0100_stafftask_suspended_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'base_manager_name': 'all_objects', 'ordering': ['-opened_at', '-created_at', '-id'], 'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'base_manager_name': 'all_objects', 'permissions': [('view_sensitive_data', 'Can view sensitive and encrypted PII data')]},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'base_manager_name': 'all_objects', 'ordering': ['-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelManagers(
            name='case',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
