# Generated by Django 6.0.6 on 2026-06-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0104_client_archived_by_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="client",
            name="client_workflow_status_idx",
        ),
        migrations.RemoveField(
            model_name="client",
            name="case_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="case_number_hash",
        ),
        migrations.RemoveField(
            model_name="client",
            name="decision_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_info",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_list",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_location",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_ticket",
        ),
        migrations.RemoveField(
            model_name="client",
            name="fingerprints_time",
        ),
        migrations.RemoveField(
            model_name="client",
            name="submission_date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="workflow_stage",
        ),
    ]
