# Generated by Django 6.0.6 on 2026-06-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0105_remove_client_client_workflow_status_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="case",
            name="case_staff_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="client_staff_status_idx",
        ),
        migrations.RemoveField(
            model_name="case",
            name="assigned_staff",
        ),
        migrations.RemoveField(
            model_name="client",
            name="assigned_staff",
        ),
    ]
