# Generated by Django 6.0.6 on 2026-06-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0106_remove_assigned_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="new_card_application_data",
        ),
    ]
