# Generated by Django 6.0.6 on 2026-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0107_remove_case_new_card_application_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="casearchivesnapshot",
            name="case_snapshot_batch_idx",
        ),
        migrations.RemoveIndex(
            model_name="casearchivesnapshot",
            name="case_snapshot_object_idx",
        ),
        migrations.RemoveConstraint(
            model_name="casearchivesnapshot",
            name="unique_case_archive_snapshot_object",
        ),
        migrations.DeleteModel(
            name="CaseArchiveSnapshot",
        ),
    ]
