# Generated by Django 6.0.6 on 2026-06-29 15:11

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0108_remove_casearchivesnapshot_case_snapshot_batch_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_review', 'Needs staff review'), ('converted', 'Converted to client/case'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=32)),
                ('source', models.CharField(choices=[('public_link', 'Public link'), ('staff_link', 'Staff link'), ('import', 'Import')], default='public_link', max_length=32)),
                ('personal_data', fernet_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('case_data', fernet_fields.fields.EncryptedJSONField(blank=True, default=dict)),
                ('staff_notes', models.TextField(blank=True)),
                ('email_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('phone_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('passport_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_intake_submissions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intake_submissions', to=settings.AUTH_USER_MODEL)),
                ('created_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='clients.case')),
                ('created_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='intake_status_created_idx'), models.Index(fields=['email_hash', 'status'], name='intake_email_status_idx'), models.Index(fields=['phone_hash', 'status'], name='intake_phone_status_idx'), models.Index(fields=['passport_hash', 'status'], name='intake_passport_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'converted'), _negated=True), models.Q(('created_client__isnull', False), ('created_case__isnull', False)), _connector='OR'), name='intake_converted_has_client_case')],
            },
        ),
    ]
