# Generated by Django 6.0.6 on 2026-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0109_clientintakesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="family_role",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Роль в семейном деле",
            ),
        ),
    ]
