# Generated by Django 6.0.6 on 2026-07-01 13:14

from django.db import migrations, models

VALID_FAMILY_ROLES = {"sponsor", "family_spouse", "family_child"}


def backfill_case_family_role(apps, schema_editor):
    Case = apps.get_model("clients", "Case")
    Client = apps.get_model("clients", "Client")

    clients_with_role = Client.objects.exclude(family_role="").exclude(family_role__isnull=True)
    for client in clients_with_role.iterator():
        role = str(client.family_role or "")
        if role not in VALID_FAMILY_ROLES:
            continue
        cases = list(Case.objects.filter(client_id=client.pk).only("id", "application_purpose", "family_role")[:2])
        if len(cases) != 1:
            continue
        case = cases[0]
        if case.application_purpose != "family" or case.family_role:
            continue
        Case.objects.filter(pk=case.pk, family_role="").update(family_role=role)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0110_case_family_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="family_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sponsor", "Sponsor"),
                    ("family_spouse", "Spouse"),
                    ("family_child", "Child"),
                ],
                default="",
                max_length=32,
                verbose_name="Роль в семейном деле",
            ),
        ),
        migrations.RunPython(backfill_case_family_role, noop_reverse),
    ]
