# Generated by Django 6.0.6 on 2026-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0111_backfill_case_family_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosapplicationdata",
            name="new_residence_card_application_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not provided"),
                    ("yes", "Да"),
                    ("no", "Нет"),
                    ("unknown", "Не знаю"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
