# Generated by Django 6.0.6 on 2026-07-05 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0113_backfill_case_for_legacy_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="data_controller_krs",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="KRS"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="data_controller_nip",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="NIP"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="data_controller_regon",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="REGON"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="dpo_contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email или иной контакт инспектора по защите данных, если назначен.",
                max_length=255,
                verbose_name="Контакт инспектора по защите данных (IOD/DPO)",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="legal_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Одна строка на строку. Юридический адрес администратора данных.",
                verbose_name="Юридический адрес",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="legal_entity_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Полное юридическое наименование администратора персональных данных.",
                max_length=255,
                verbose_name="Администратор данных (юр. лицо)",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="privacy_policy_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например, 2026-01. Фиксируется в записи согласия, чтобы можно было доказать, с какой редакцией политики согласился субъект данных.",
                max_length=32,
                verbose_name="Версия политики конфиденциальности",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="representative_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ФИО и должность лица, представляющего администратора данных.",
                max_length=255,
                verbose_name="Представитель",
            ),
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("data_processing", "Обработка персональных данных"),
                            ("service_provision", "Оказание услуг по делу"),
                            ("marketing", "Маркетинговые сообщения"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True,
                        help_text="True — согласие дано; False — согласие отозвано.",
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("onboarding", "Онбординг"),
                            ("signup", "Регистрация"),
                            ("staff", "Сотрудник"),
                            ("portal", "Личный кабинет"),
                        ],
                        default="onboarding",
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to="clients.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись согласия",
                "verbose_name_plural": "Записи согласия",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "purpose", "-created_at"],
                        name="clients_con_client__beed96_idx",
                    )
                ],
            },
        ),
    ]
