# Generated by Django 6.0.6 on 2026-07-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0114_appsettings_data_controller_krs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="data_retention_summary",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кратко: как долго хранятся данные. Показывается в политике.",
                max_length=255,
                verbose_name="Срок хранения данных",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="privacy_policy_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Необязательно. Дополнительный текст политики, который показывается на публичной странице под стандартными разделами RODO.",
                verbose_name="Текст политики конфиденциальности",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="erasure_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Запрос на удаление данных"
            ),
        ),
    ]
