# Generated by Django 6.0.6 on 2026-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0115_appsettings_data_retention_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="erasure_fulfilled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата исполнения удаления"
            ),
        ),
    ]
