# Generated by Django 6.0.6 on 2026-07-07 11:34

import hashlib
import hmac

from django.conf import settings
from django.db import migrations, models

_HASH_SEP = "\x1f"


def _hash(canonical: str) -> str:
    secret = str(getattr(settings, "SECRET_KEY", ""))
    return hmac.new(secret.encode("utf-8"), canonical.encode("utf-8"), hashlib.sha256).hexdigest()


def backfill_consent_hash_chain(apps, schema_editor):
    """Seed the per-client hash chain for consent rows that predate the feature.

    Mirrors ConsentRecord._canonical_payload so freshly-hashed history verifies
    with ConsentRecord.verify_chain going forward.
    """
    ConsentRecord = apps.get_model("clients", "ConsentRecord")
    rows = ConsentRecord.objects.order_by("client_id", "created_at", "id")
    prev_by_client: dict[int, str] = {}
    updated = []
    for row in rows.iterator():
        prev = prev_by_client.get(row.client_id, "")
        canonical = _HASH_SEP.join(
            [
                str(row.client_id or ""),
                str(row.purpose or ""),
                "1" if row.granted else "0",
                str(row.policy_version or ""),
                str(row.channel or ""),
                str(row.ip_address or ""),
                str(row.user_agent or ""),
                row.created_at.isoformat() if row.created_at else "",
                prev,
            ]
        )
        entry = _hash(canonical)
        row.prev_hash = prev
        row.entry_hash = entry
        prev_by_client[row.client_id] = entry
        updated.append(row)
    if updated:
        ConsentRecord.objects.bulk_update(updated, ["prev_hash", "entry_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0116_client_erasure_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="entry_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="prev_hash",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.RunPython(backfill_consent_hash_chain, migrations.RunPython.noop),
    ]
