# Generated by Django 6.0.6 on 2026-07-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_erasure_status(apps, schema_editor):
    """Map existing timestamp-only requests onto the new status field.

    Already-fulfilled clients → 'fulfilled'; open requests → 'requested'. Pending
    requests intentionally land in 'requested' (not 'approved'), so the new
    approval gate applies to them too.
    """
    Client = apps.get_model("clients", "Client")
    Client.objects.filter(erasure_fulfilled_at__isnull=False).update(erasure_status="fulfilled")
    Client.objects.filter(
        erasure_requested_at__isnull=False, erasure_fulfilled_at__isnull=True
    ).update(erasure_status="requested")


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0117_consentrecord_entry_hash_consentrecord_prev_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="erasure_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата одобрения удаления"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="erasure_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_erasures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Одобрил удаление",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="erasure_decision_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Причина решения по удалению",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="erasure_status",
            field=models.CharField(
                choices=[
                    ("none", "Нет запроса"),
                    ("requested", "Запрошено субъектом"),
                    ("approved", "Одобрено к стиранию"),
                    ("rejected", "Отклонено"),
                    ("fulfilled", "Выполнено"),
                ],
                db_index=True,
                default="none",
                max_length=16,
                verbose_name="Статус запроса на удаление",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="legal_hold",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Юридическая блокировка (legal hold)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="legal_hold_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Причина юридической блокировки",
            ),
        ),
        migrations.RunPython(backfill_erasure_status, migrations.RunPython.noop),
    ]
