# Generated by Django 6.0.6 on 2026-07-10 13:32

from django.db import migrations, models


def _backfill_actor_label(apps, schema_editor):
    """Snapshot the actor identity onto existing rows that still have an actor."""
    ClientActivity = apps.get_model("clients", "ClientActivity")
    rows = ClientActivity.objects.filter(actor__isnull=False).exclude(actor_label__gt="").select_related("actor")
    to_update = []
    for row in rows.iterator():
        actor = row.actor
        email = (getattr(actor, "email", "") or "").strip()
        first = (getattr(actor, "first_name", "") or "").strip()
        last = (getattr(actor, "last_name", "") or "").strip()
        name = f"{first} {last}".strip()
        if name and email:
            label = f"{name} <{email}>"
        else:
            label = email or name or f"user#{actor.pk}"
        row.actor_label = label[:255]
        to_update.append(row)
        if len(to_update) >= 500:
            ClientActivity.objects.bulk_update(to_update, ["actor_label"])
            to_update = []
    if to_update:
        ClientActivity.objects.bulk_update(to_update, ["actor_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0118_client_erasure_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientactivity",
            name="actor_label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Кто выполнил"
            ),
        ),
        migrations.RunPython(_backfill_actor_label, migrations.RunPython.noop),
    ]
