# Generated by Django 6.0.7 on 2026-07-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _label(user) -> str:
    if user is None:
        return ""
    email = (getattr(user, "email", "") or "").strip()
    first = (getattr(user, "first_name", "") or "").strip()
    last = (getattr(user, "last_name", "") or "").strip()
    name = f"{first} {last}".strip()
    if name and email:
        return f"{name} <{email}>"[:255]
    return (email or name or f"user#{user.pk}")[:255]


def _backfill_labels(apps, schema_editor):
    StaffAuditEvent = apps.get_model("clients", "StaffAuditEvent")
    rows = StaffAuditEvent.objects.select_related("actor", "target")
    to_update = []
    for row in rows.iterator():
        changed = False
        if not row.actor_label and row.actor_id:
            row.actor_label = _label(row.actor)
            changed = True
        if not row.target_label and row.target_id:
            row.target_label = _label(row.target)
            changed = True
        if changed:
            to_update.append(row)
        if len(to_update) >= 500:
            StaffAuditEvent.objects.bulk_update(to_update, ["actor_label", "target_label"])
            to_update = []
    if to_update:
        StaffAuditEvent.objects.bulk_update(to_update, ["actor_label", "target_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0119_add_activity_actor_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffauditevent",
            name="actor_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="staffauditevent",
            name="target_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="staffauditevent",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_staff_audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(_backfill_labels, migrations.RunPython.noop),
    ]
