# Generated by Django 6.0.7 on 2026-07-10 16:32

from django.db import migrations


def _backfill_reminder_case(apps, schema_editor):
    """Attach a Case to legacy reminders that predate case-scoping.

    Only fills unambiguous cases: the case implied by the reminder's source
    object (payment/document/custom requirement), or — when the client has
    exactly one case — that case. Reminders on a multi-case client with no
    source stay null rather than being pointed at an arbitrary case.
    """
    Reminder = apps.get_model("clients", "Reminder")
    Client = apps.get_model("clients", "Client")

    single_case_by_client: dict[int, int] = {}
    to_update = []
    orphans = Reminder.objects.filter(case__isnull=True).select_related(
        "payment", "document", "custom_document_requirement"
    )
    for reminder in orphans.iterator():
        case_id = None
        for source in (reminder.payment, reminder.document, reminder.custom_document_requirement):
            source_case_id = getattr(source, "case_id", None) if source is not None else None
            if source_case_id:
                case_id = source_case_id
                break
        if case_id is None and reminder.client_id:
            if reminder.client_id not in single_case_by_client:
                case_ids = list(
                    Client.objects.get(pk=reminder.client_id).cases.values_list("id", flat=True)
                )
                single_case_by_client[reminder.client_id] = case_ids[0] if len(case_ids) == 1 else 0
            resolved = single_case_by_client[reminder.client_id]
            if resolved:
                case_id = resolved
        if case_id is not None:
            reminder.case_id = case_id
            to_update.append(reminder)
        if len(to_update) >= 500:
            Reminder.objects.bulk_update(to_update, ["case"])
            to_update = []
    if to_update:
        Reminder.objects.bulk_update(to_update, ["case"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0120_staffauditevent_target_setnull_labels"),
    ]

    operations = [
        migrations.RunPython(_backfill_reminder_case, migrations.RunPython.noop),
    ]
