# Generated by Django 6.0.7 on 2026-07-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0122_backfill_case_application_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="confirms_submission",
            field=models.ForeignKey(
                blank=True,
                help_text="Подача (wniosek), позиции которой закрывает этот штамп/подтверждение подачи.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proof_documents",
                to="clients.wnioseksubmission",
                verbose_name="Подтверждает подачу",
            ),
        ),
    ]
