# Generated by Django 6.0.7 on 2026-07-21 06:03

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0125_repair_ocr_name_mismatch_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSearchToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
            ],
            options={
                "verbose_name": "Поисковый токен клиента",
                "verbose_name_plural": "Поисковые токены клиентов",
            },
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="client_email_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="client_phone_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="client_name_idx",
        ),
        migrations.AddField(
            model_name="client",
            name="email_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="phone_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=fernet_fields.fields.EncryptedTextField(verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=fernet_fields.fields.EncryptedTextField(verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=fernet_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="clientsearchtoken",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_tokens",
                to="clients.client",
            ),
        ),
        migrations.AddIndex(
            model_name="clientsearchtoken",
            index=models.Index(
                fields=["token_hash"], name="client_search_token_hash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientsearchtoken",
            constraint=models.UniqueConstraint(
                fields=("client", "token_hash"), name="uniq_client_search_token"
            ),
        ),
    ]
