# Generated by Django 6.0.7 on 2026-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0127_encrypt_client_identity_pii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("client_viewed", "Карточка клиента открыта"),
                    ("client_created", "Клиент создан"),
                    ("client_updated", "Данные клиента изменены"),
                    ("client_status_changed", "Статус клиента изменён"),
                    ("client_archived", "Клиент архивирован"),
                    ("client_restored", "Клиент восстановлен"),
                    ("case_updated", "Дело обновлено"),
                    ("case_archived", "Дело архивировано"),
                    ("case_restored", "Дело восстановлено"),
                    ("workflow_changed", "Этап workflow изменён"),
                    ("workflow_stage_changed", "Этап дела изменён"),
                    ("deadline_changed", "Ключевая дата изменена"),
                    ("document_uploaded", "Документ загружен"),
                    ("document_downloaded", "Документ открыт"),
                    ("document_deleted", "Документ удалён"),
                    ("document_verified", "Статус документа изменён"),
                    ("document_updated", "Документ обновлён"),
                    ("document_confirmed", "Данные документа подтверждены"),
                    ("document_version_restored", "Версия документа восстановлена"),
                    ("email_sent", "Письмо отправлено"),
                    ("client_exported", "Данные клиента экспортированы"),
                    ("wniosek_attachment_deleted", "Отметка wniosek удалена"),
                    ("wniosek_updated", "Wniosek обновлён"),
                    ("reminder_deactivated", "Напоминание отмечено выполненным"),
                    ("reminder_deleted", "Напоминание удалено"),
                    ("reminder_updated", "Напоминание обновлено"),
                    ("payment_created", "Платёж создан"),
                    ("payment_updated", "Платёж обновлён"),
                    ("payment_deleted", "Платёж удалён"),
                    ("task_created", "Задача создана"),
                    ("task_completed", "Задача завершена"),
                    ("task_updated", "Задача обновлена"),
                    ("note_updated", "Заметка обновлена"),
                    ("new_card_application_updated", "Новая подача обновлена"),
                    ("mos_updated", "Данные MOS обновлены"),
                    ("mos_data_applied", "Данные MOS применены"),
                    ("pesel_updated", "Заявка PESEL обновлена"),
                    ("requirement_updated", "Требование документа обновлено"),
                    ("comment", "Комментарий клиента"),
                ],
                max_length=50,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="staffauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("staff_updated", "Staff user updated"),
                    ("staff_active_toggled", "Staff active status toggled"),
                    ("test_center_run", "Test Center run"),
                    ("test_center_cleanup", "Test Center cleanup"),
                    ("demo_center_run", "Demo Center run"),
                ],
                max_length=64,
            ),
        ),
    ]
