# Generated by Django 6.0.1 on 2026-04-20 21:10

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_add_localized_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='submission_documents/', validators=[clients.validators.validate_uploaded_document], verbose_name='Файл'),
        ),
    ]
