# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseMediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=512, unique=True)),
                ("content", models.BinaryField()),
                ("content_type", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "database media file",
                "verbose_name_plural": "database media files",
                "ordering": ["name"],
            },
        ),
    ]
