from clients.views.base import StaffRequiredMixin, staff_required_view
from clients.views.clients import (
    ClientCreateView,
    ClientDeleteView,
    ClientDetailView,
    ClientListView,
    AppSettingsUpdateView,
    AdminPanelView,
    ClientUpdateView,
    DocumentChecklistManageView,
    document_requirement_add,
    document_requirement_edit,
    document_requirement_delete,
    calculator_view,
    service_price_manage_view,
    staff_manage_view,
    submission_manage_view,
    DocumentTemplateHubView,
    role_manage_view,
    client_print_view,
    client_document_print_view,
    client_document_print_confirm_view,
    client_wsc_print_view,
    dashboard_redirect_view,
)
from clients.views.documents import (
    add_document,
    client_checklist_partial,
    client_overview_partial,
    client_status_api,
    confirm_wezwanie_parse,
    document_download,
    document_delete,
    wniosek_attachment_delete,
    toggle_document_verification,
    verify_all_documents,
    update_client_notes,
)
from clients.views.emails import (
    email_preview_api,
    send_custom_email,
    mass_email_view,
    campaign_status_api,
)
from clients.views.payments import add_payment, delete_payment, edit_payment, get_price_for_service
from clients.views.tasks import TaskListView, add_task, complete_task
from clients.views.reminders import (
    DocumentReminderListView,
    PaymentReminderListView,
    reminder_action,
    run_update_reminders,
    send_document_reminder_email,
)
from clients.views.metrics import MetricsDashboardView
from clients.views.admin_dashboard import AdminDashboardView
from clients.views.export import (
    client_export_pdf_view,
    client_export_zip,
    document_versions_view,
    document_version_restore,
)

__all__ = [
    'StaffRequiredMixin',
    'staff_required_view',
    'ClientCreateView',
    'ClientDeleteView',
    'ClientDetailView',
    'ClientListView',
    'AppSettingsUpdateView',
    'AdminPanelView',
    'ClientUpdateView',
    'DocumentChecklistManageView',
    'document_requirement_add',
    'document_requirement_edit',
    'document_requirement_delete',
    'calculator_view',
    'service_price_manage_view',
    'staff_manage_view',
    'submission_manage_view',
    'DocumentTemplateHubView',
    'role_manage_view',
    'client_print_view',
    'client_document_print_view',
    'client_document_print_confirm_view',
    'client_wsc_print_view',
    'dashboard_redirect_view',
    'add_document',
    'client_checklist_partial',
    'client_overview_partial',
    'client_status_api',
    'confirm_wezwanie_parse',
    'document_download',
    'document_delete',
    'wniosek_attachment_delete',
    'toggle_document_verification',
    'verify_all_documents',
    'update_client_notes',
    'add_payment',
    'delete_payment',
    'edit_payment',
    'get_price_for_service',
    'TaskListView',
    'add_task',
    'complete_task',
    'DocumentReminderListView',
    'PaymentReminderListView',
    'reminder_action',
    'run_update_reminders',
    'send_document_reminder_email',
    'MetricsDashboardView',
    'mass_email_view',
    'campaign_status_api',
    'AdminDashboardView',
    'client_export_pdf_view',
    'client_export_zip',
    'document_versions_view',
    'document_version_restore',
]
