# Generated by Django 5.1.7 on 2025-07-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('passport_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер паспорта')),
                ('application_purpose', models.CharField(choices=[('study', 'Учёба'), ('work', 'Работа'), ('family', 'Воссоединение семьи')], default='study', max_length=20, verbose_name='Цель подачи')),
                ('basis_of_stay', models.CharField(blank=True, max_length=100, null=True, verbose_name='Основание пребывания (виза, TRC и т.д.)')),
                ('language', models.CharField(choices=[('pl', 'Польский'), ('en', 'Английский'), ('ru', 'Русский')], default='pl', max_length=5, verbose_name='Язык документов')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('legal_basis_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания основания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Uwagi / Заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт'), ('certificate_enrolment', 'Справка о зачислении'), ('certificate_fees', 'Справка об оплате обучения'), ('health_insurance', 'Медицинская страховка'), ('rental_contract', 'Договор аренды'), ('financial_means', 'Документ о средствах'), ('work_permit', 'Разрешение на работу (Залончник №1)'), ('employment_contract', 'Трудовой договор'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
