# Generated by Django 5.1.7 on 2025-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='basis',
            new_name='legal_basis',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В ожидании'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('residence', 'Вид на жительство'), ('visa', 'Виза'), ('other', 'Другое')], max_length=20),
        ),
    ]
