# Generated by Django 5.1.7 on 2025-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер дела'),
        ),
    ]
