# Generated by Django 5.1.7 on 2025-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_basis_client_legal_basis_alter_client_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('pl', 'Польский'), ('en', 'Английский'), ('ru', 'Русский')], default='pl', max_length=5),
        ),
        migrations.AddField(
            model_name='document',
            name='is_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_basis',
            field=models.CharField(choices=[('study', 'Учёба'), ('work', 'Работа')], default='study', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('certificate_enrolment', 'Справка о зачислении'), ('certificate_fees', 'Справка об оплате обучения'), ('class_schedule', 'Расписание занятий'), ('attendance_record', 'Посещаемость'), ('transcript_grades', 'Выписка оценок'), ('payment_proof', 'Подтверждение оплаты'), ('health_insurance', 'Медицинская страховка'), ('rental_contract', 'Договор аренды'), ('housing_expenses', 'Коммунальные платежи'), ('financial_means', 'Документ о средствах'), ('other', 'Другое')], max_length=50),
        ),
    ]
