# Generated by Django 5.1.7 on 2025-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон работодателя'),
        ),
        migrations.AddField(
            model_name='client',
            name='fingerprints_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи отпечатков'),
        ),
    ]
