# Generated by Django 5.1.7 on 2025-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_language_document_is_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='apply_for',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем или для чего подаёт'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_basis_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания основания'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
