# Generated by Django 5.1.7 on 2025-07-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_apply_for_client_legal_basis_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_type',
            new_name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_provided',
        ),
    ]
