# Generated by Django 5.1.7 on 2025-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_payment_payment_date_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Оплатить до'),
        ),
    ]
