# Generated by Django 5.1.7 on 2025-07-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_payment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('payment', 'Оплата'), ('document', 'Документ'), ('other', 'Другое')], default='document', max_length=20, verbose_name='Тип напоминания')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок напоминания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('due_date', models.DateField(verbose_name='Ключевая дата (окончание/оплата до)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
