# Generated by Django 5.1.7 on 2025-07-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service_description',
            field=models.CharField(choices=[('work_permit', 'Работа'), ('student_visa', 'Учёба'), ('photo_service', 'Фото'), ('consultation', 'Консультация')], max_length=100, verbose_name='Описание услуги'),
        ),
    ]
