# Generated by Django 5.1.7 on 2025-07-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_payment_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='clients.payment'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(verbose_name='Ключевая дата'),
        ),
    ]
