# Generated by Django 5.1.7 on 2025-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_document_verified_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('photos', 'Фотографии'), ('payment_confirmation', 'Подтверждение оплаты'), ('passport', 'Паспорт'), ('enrollment_certificate', 'Справка о зачислении'), ('tuition_fee_proof', 'Справка об оплате обучения'), ('health_insurance', 'Медицинская страховка'), ('address_proof', 'Подтверждение адреса'), ('financial_proof', 'Подтверждение финансов'), ('załącznik_nr_1', 'Załącznik nr 1'), ('starosta_info', 'Informacja starosty'), ('employment_contract', 'Трудовой договор'), ('pit_proof', 'PIT-37 / Zaświadczenie o niezaleganiu')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_description',
            field=models.CharField(choices=[('work_service', 'Сопровождение (Работа)'), ('study_service', 'Сопровождение (Учеба)'), ('consultation', 'Консультация'), ('document_preparation', 'Подготовка документов'), ('full_service', 'Полное сопровождение'), ('deposit', 'Задаток'), ('other', 'Другое')], max_length=100, verbose_name='Описание услуги'),
        ),
    ]
