# Generated by Django 6.0.4 on 2026-05-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.TextField(db_index=True, verbose_name='Original text (msgid)')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('pl', 'Polish'), ('en', 'English')], db_index=True, max_length=10)),
                ('text', models.TextField(blank=True, verbose_name='Translated text')),
                ('source', models.CharField(choices=[('studio', 'Translation Studio'), ('import', 'Imported from PO'), ('manual', 'Manual')], default='studio', max_length=32)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_override_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Override',
                'verbose_name_plural': 'Translation Overrides',
                'ordering': ['language', 'msgid'],
                'indexes': [models.Index(fields=['language', 'msgid'], name='trans_lang_msgid_idx'), models.Index(fields=['is_active', 'language'], name='trans_active_lang_idx')],
                'constraints': [models.UniqueConstraint(fields=('msgid', 'language'), name='unique_translation_override_msgid_lang')],
            },
        ),
    ]
