# Generated by Django 6.0.4 on 2026-05-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.TextField(db_index=True, verbose_name='Original text (msgid)')),
                ('language', models.CharField(db_index=True, max_length=10, verbose_name='Language code')),
                ('text', models.TextField(blank=True, verbose_name='Translated text')),
                ('source', models.CharField(default='studio', max_length=32, verbose_name='Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Translation Override',
                'verbose_name_plural': 'Translation Overrides',
                'ordering': ['language', 'msgid'],
                'indexes': [models.Index(fields=['language', 'msgid'], name='trans_lang_msgid_idx'), models.Index(fields=['is_active', 'language'], name='trans_active_lang_idx')],
                'unique_together': {('msgid', 'language')},
            },
        ),
    ]
