# Generated by Django 6.0.4 on 2026-05-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.TextField(verbose_name='Source text / msgid')),
                ('language_code', models.CharField(choices=[('ru', 'Russian'), ('pl', 'Polish'), ('en', 'English')], db_index=True, max_length=10)),
                ('msgstr', models.TextField(blank=True, verbose_name='Translated text / msgstr')),
                ('source', models.CharField(choices=[('studio', 'Translation Studio'), ('import', 'Imported from PO'), ('manual', 'Manual')], default='studio', max_length=32)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Runtime translation',
                'verbose_name_plural': 'Runtime translations',
                'ordering': ['msgid', 'language_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='translationoverride',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='translationoverride',
            name='trans_lang_msgid_idx',
        ),
        migrations.RemoveIndex(
            model_name='translationoverride',
            name='trans_active_lang_idx',
        ),
        migrations.AddField(
            model_name='runtimetranslation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_translation_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='translationoverride',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='runtimetranslation',
            index=models.Index(fields=['language_code', 'updated_at'], name='runtime_tr_lang_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='runtimetranslation',
            index=models.Index(fields=['is_active', 'language_code'], name='runtime_tr_active_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='runtimetranslation',
            constraint=models.UniqueConstraint(fields=('msgid', 'language_code'), name='unique_runtime_translation_msgid_lang'),
        ),
        migrations.DeleteModel(
            name='TranslationOverride',
        ),
    ]
